setwd("D:/1. KULIAH/SEMESTER 8/INTRODUCTION TO R")
macarooData <- read.csv("data_1719010.csv")
View(macarooData)
meanAge <- mean(macarooData$age)
meanSalary <- mean(macarooData$salary)
meanSpendingOnFood <- mean(macarooData$spending_on_food)
meanSpendingOnEntertainment <- mean(macarooData$spending_on_entertainment)
print(meanAge)

medianAge <- median(macarooData$age)
medianSalary <- median(macarooData$salary)
medianSpendingOnFood <- median(macarooData$spending_on_food)
medianSpendingOnEntertainment <- median(macarooData$spending_on_entertainment)
minAge <- min(macarooData$age)
minSalary <- min(macarooData$salary)
minSpendingOnFood <- min(macarooData$spending_on_food)
minSpendingOnEntertainment <- min(macarooData$spending_on_entertainment)
print(minAge)

maxAge <- max(macarooData$age)
maxSalary <- max(macarooData$salary)
maxSpendingOnFood <- max(macarooData$spending_on_food)
maxSpendingOnEntertainment <- max(macarooData$spending_on_entertainment)
print(macarooData)